### ISSUE TITLE
关于解决宋体无法加粗问题的设置

### ISSUE THREAD

**Issue by yangtzech** [1FCENdoge/SYSUThesis#2]
如果在windows上，编译没有问题，但如果是在ubuntu上，尽快安装了宋体还是会报错，找不到simsun.ttc文件

如果将`\setCJKmainfont{simsun.ttc}[AutoFakeBold] `改成`\setCJKmainfont{SimSun}[AutoFakeBold] `则可以正常编译

**Comment by 1FCENdoge** [comment]
已解决
