### ISSUE TITLE
notoccite宏包失效

### ISSUE THREAD

**Issue by 1FCENdoge** [1FCENdoge/SYSUThesis#22]
在.cls文件中添加notoccite宏包后，文献引用依然从目录开始
![image](https://github.com/1FCENdoge/SYSUThesis/assets/86185801/60b1f244-3970-4546-bafd-c129e79a4077)
![image](https://github.com/1FCENdoge/SYSUThesis/assets/86185801/bc6220c9-ae2e-4f01-9b50-96273d8bd925)

**Comment by Immortalyzy** [comment]
check https://tex.stackexchange.com/questions/351911/the-usepackage-notoccite-does-not-work

**Comment by 1FCENdoge** [comment]
哦，我知道了，插图目录是可以出现引用的，我以为插图目录不能出现引用的标，我搞错了，此issue结束。
