### ISSUE TITLE
\mathcal{}编译问题

### ISSUE THREAD

**Issue by LuoJMs** [1FCENdoge/SYSUThesis#25]
\mathcal{}编译出来的是\mathscr{}的字体，有什么解决办法吗

**Comment by 1FCENdoge** [comment]
是在overleaf还是在本地texlive中编译遇到的？

**Comment by 1FCENdoge** [comment]
尝试一下本地texlive编译，这种字体问题很多是因为overleaf没有导致的，一般windows中会有
我下周有时间了看看

**Comment by 1FCENdoge** [comment]
> \mathcal{}编译出来的是\mathscr{}的字体，有什么解决办法吗

在.cls文件中如下位置加入这行代码便能区分两种字体：
![image](https://github.com/1FCENdoge/SYSUThesis/assets/86185801/51500733-73b7-4500-b4e3-c918c7b22752)
但是通常情况下没必要也不需要这么做，具体原因请见[此处](https://zhuanlan.zhihu.com/p/569922028)。
p.s. 这个修改也是来自这个知乎回答。
如果实在不需要的话就仅当技术讨论了，此issue不会带来新的提交。
