### ISSUE TITLE
在使用Overleaf编译时出现的问题

### ISSUE THREAD

**Issue by HuguesSYSU** [1FCENdoge/SYSUThesis#27]
我将.zip上传到Overleaf并将编译器指定为XeLaTex，出现以下错误：Package fontspec Error: The font "SimSun" cannot be found.
我也尝试了上传相应的字体（SimSun.ttf）以及修改.cls文件中的\setCJKmainfont{SimSun}[AutoFakeBold]为\setCJKmainfont{SimSun.ttf}[AutoFakeBold]，均无法成功编译。

我正在初学LaTex，如果其中有什么默认采取而我未采取的措施，请不吝告知。

等待你的回复。

**Comment by 1FCENdoge** [comment]
这是由于windows上texlive和overleaf的设置不同导致的，只需对sysuthesis.cls文件中开头几行进行修改即可，如图是修改的方式，注意开头标黄的几行：
![image](https://github.com/user-attachments/assets/aaa8301f-a1f3-4c43-85da-4962b772eb34)
后期项目将专注在windows上texlive的编译，以便实现项目中某些想要的效果。
